// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1) {
  return window['go']['state']['WailsBindings']['AddTodo'](arg1);
}

export function CheckLocalAIHealth() {
  return window['go']['state']['WailsBindings']['CheckLocalAIHealth']();
}

export function CheckOllamaHealth() {
  return window['go']['state']['WailsBindings']['CheckOllamaHealth']();
}

export function CheckOpenAIHealth() {
  return window['go']['state']['WailsBindings']['CheckOpenAIHealth']();
}

export function GetAppState() {
  return window['go']['state']['WailsBindings']['GetAppState']();
}

export function GetAvailableTools() {
  return window['go']['state']['WailsBindings']['GetAvailableTools']();
}

export function GetContextUsage() {
  return window['go']['state']['WailsBindings']['GetContextUsage']();
}

export function GetLocalAIConfig() {
  return window['go']['state']['WailsBindings']['GetLocalAIConfig']();
}

export function GetMCPStatus() {
  return window['go']['state']['WailsBindings']['GetMCPStatus']();
}

export function GetMessages() {
  return window['go']['state']['WailsBindings']['GetMessages']();
}

export function GetOllamaConfig() {
  return window['go']['state']['WailsBindings']['GetOllamaConfig']();
}

export function GetOpenAIConfig() {
  return window['go']['state']['WailsBindings']['GetOpenAIConfig']();
}

export function GetProjectDirectory() {
  return window['go']['state']['WailsBindings']['GetProjectDirectory']();
}

export function GetSessionID() {
  return window['go']['state']['WailsBindings']['GetSessionID']();
}

export function Interrupt() {
  return window['go']['state']['WailsBindings']['Interrupt']();
}

export function ListAvailableModels() {
  return window['go']['state']['WailsBindings']['ListAvailableModels']();
}

export function ListDirectoryContents(arg1) {
  return window['go']['state']['WailsBindings']['ListDirectoryContents'](arg1);
}

export function ListLocalAIMCPServers(arg1) {
  return window['go']['state']['WailsBindings']['ListLocalAIMCPServers'](arg1);
}

export function ListLocalAIModels() {
  return window['go']['state']['WailsBindings']['ListLocalAIModels']();
}

export function ListOpenAIModels() {
  return window['go']['state']['WailsBindings']['ListOpenAIModels']();
}

export function RefreshContext() {
  return window['go']['state']['WailsBindings']['RefreshContext']();
}

export function RegisterMCPTool(arg1) {
  return window['go']['state']['WailsBindings']['RegisterMCPTool'](arg1);
}

export function SelectProjectDirectory() {
  return window['go']['state']['WailsBindings']['SelectProjectDirectory']();
}

export function SendMessage(arg1) {
  return window['go']['state']['WailsBindings']['SendMessage'](arg1);
}

export function SetEngine(arg1) {
  return window['go']['state']['WailsBindings']['SetEngine'](arg1);
}

export function SetFastMode(arg1) {
  return window['go']['state']['WailsBindings']['SetFastMode'](arg1);
}

export function SetLocalAIConfig(arg1) {
  return window['go']['state']['WailsBindings']['SetLocalAIConfig'](arg1);
}

export function SetModel(arg1) {
  return window['go']['state']['WailsBindings']['SetModel'](arg1);
}

export function SetOllamaConfig(arg1) {
  return window['go']['state']['WailsBindings']['SetOllamaConfig'](arg1);
}

export function SetOpenAIConfig(arg1) {
  return window['go']['state']['WailsBindings']['SetOpenAIConfig'](arg1);
}

export function SetPermissionMode(arg1) {
  return window['go']['state']['WailsBindings']['SetPermissionMode'](arg1);
}

export function SetProjectDirectory(arg1) {
  return window['go']['state']['WailsBindings']['SetProjectDirectory'](arg1);
}

export function SetThinking(arg1) {
  return window['go']['state']['WailsBindings']['SetThinking'](arg1);
}

export function SetToolRegistry(arg1) {
  return window['go']['state']['WailsBindings']['SetToolRegistry'](arg1);
}

export function Startup(arg1) {
  return window['go']['state']['WailsBindings']['Startup'](arg1);
}

export function UpdateTodoStatus(arg1, arg2) {
  return window['go']['state']['WailsBindings']['UpdateTodoStatus'](arg1, arg2);
}
