// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {state} from '../models';
import {registry} from '../models';
import {context} from '../models';

export function AddTodo(arg1:state.TodoRequest):Promise<void>;

export function CheckOllamaHealth():Promise<state.OllamaHealthResponse>;

export function GetAppState():Promise<state.AppStateSnapshot>;

export function GetAvailableTools():Promise<Array<state.ToolInfo>>;

export function GetMCPStatus():Promise<state.MCPState>;

export function GetMessages():Promise<state.GetMessagesResponse>;

export function GetOllamaConfig():Promise<state.OllamaConfigRequest>;

export function GetSessionID():Promise<string>;

export function Interrupt():Promise<void>;

export function ListAvailableModels():Promise<state.ListModelsResponse>;

export function RefreshContext():Promise<void>;

export function RegisterMCPTool(arg1:state.RegisterToolRequest):Promise<void>;

export function SendMessage(arg1:state.SendMessageRequest):Promise<state.SendMessageResponse>;

export function SetEngine(arg1:state.MessageSubmitter):Promise<void>;

export function SetFastMode(arg1:state.SetFastModeRequest):Promise<void>;

export function SetModel(arg1:state.SetModelRequest):Promise<void>;

export function SetOllamaConfig(arg1:state.OllamaConfigRequest):Promise<void>;

export function SetPermissionMode(arg1:state.SetPermissionModeRequest):Promise<void>;

export function SetThinking(arg1:state.SetThinkingRequest):Promise<void>;

export function SetToolRegistry(arg1:registry.ToolRegistry):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateTodoStatus(arg1:string,arg2:string):Promise<void>;
