package filewrite

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/auto-code/auto-code/internal/tools"
	"github.com/auto-code/auto-code/internal/types"
)

const (
	toolName        = "Write"
	maxResultChars  = 100000
	descriptionText = "Writes a file to the local filesystem."
)

type FileWriteInput struct {
	FilePath      string `json:"file_path"`
	Content       string `json:"content"`
	AutoGenerated bool   `json:"auto_generated,omitempty"`
}

type FileWriteOutput struct {
	Type         string  `json:"type"`
	FilePath     string  `json:"filePath"`
	Content      string  `json:"content"`
	OriginalFile *string `json:"originalFile,omitempty"`
}

type FileWriteTool struct {
	*tools.BaseTool
	confirmOverwrite func(ctx context.Context, filePath string) (bool, error)
}

// SetConfirmOverwriteHandler 注入覆盖确认回调。当最终结果文件（auto_generated=false）
// 已存在时调用，返回 true 表示用户选择覆盖。未注入时安全默认为不覆盖（追加时间戳）。
func (t *FileWriteTool) SetConfirmOverwriteHandler(handler func(ctx context.Context, filePath string) (bool, error)) {
	t.confirmOverwrite = handler
}

func NewFileWriteTool() *FileWriteTool {
	t := &FileWriteTool{
		BaseTool: tools.NewBaseTool(toolName, descriptionText, false),
	}
	t.BaseTool.ToolIsDestructive = true
	t.BaseTool.ToolIsConcurrencySafe = false
	t.BaseTool.ToolMaxResultSize = maxResultChars
	t.BaseTool.ToolSchema = buildInputSchema()
	return t
}

func buildInputSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"file_path": map[string]any{
				"type":        "string",
				"description": "The absolute or relative path to the file to write. Relative paths are resolved against the project directory. For new files, prefer placing them inside the current project directory.",
			},
			"content": map[string]any{
				"type":        "string",
				"description": "The content to write to the file",
			},
			"auto_generated": map[string]any{
				"type":        "boolean",
				"default":     false,
				"description": "Set true for intermediate/auto-generated files (e.g. helper scripts the agent creates to produce a final artifact). A unix-timestamp suffix (int64, seconds) is appended to the filename to avoid collisions. Set false (default) for final result files the user explicitly requested; if such a file already exists, the user is asked whether to overwrite, and if not, a timestamp suffix is appended instead.",
			},
		},
		"required":             []string{"file_path", "content"},
		"additionalProperties": false,
	}
}

func (t *FileWriteTool) UserFacingName(input any) string {
	if inp, ok := input.(FileWriteInput); ok {
		return inp.FilePath
	}
	return toolName
}

func (t *FileWriteTool) CheckPermissions(_ context.Context, input any, toolCtx *tools.ToolUseContext) (types.PermissionResult, error) {
	// 使用通用的权限检查函数
	result := tools.CheckToolPermission(t, toolCtx)
	if result.Behavior == types.DecisionDeny {
		return result, nil
	}
	return types.PermissionResult{Behavior: types.DecisionAllow}, nil
}

func (t *FileWriteTool) Call(ctx context.Context, input any, toolCtx *tools.ToolUseContext, onProgress tools.ToolCallProgress) (*tools.ToolResult, error) {
	var inp FileWriteInput

	// 处理不同类型的输入
	switch v := input.(type) {
	case FileWriteInput:
		inp = v
	case map[string]any:
		parsed, err := ParseFileWriteInput(v)
		if err != nil {
			return nil, fmt.Errorf("failed to parse input: %w", err)
		}
		inp = parsed
	default:
		return nil, fmt.Errorf("invalid input type for FileWriteTool: expected FileWriteInput or map[string]any, got %T", input)
	}

	filePath := expandPath(inp.FilePath)

	filePath = tools.EnsurePathInProjectDirectory(filePath, toolCtx)

	content := inp.Content

	if isUNCPath(filePath) {
		return &tools.ToolResult{Data: "UNC paths are not supported for file writing."}, nil
	}

	// 文件命名策略：
	// - 自动生成的中间文件（auto_generated=true）：一律追加时间戳后缀，避免同名冲突。
	// - 最终结果文件（auto_generated=false）：若已存在，询问用户是否覆盖；不覆盖则追加时间戳。
	if inp.AutoGenerated {
		filePath = appendTimestamp(filePath)
	} else if _, statErr := os.Stat(filePath); statErr == nil {
		overwrite := false
		if t.confirmOverwrite != nil {
			if ov, cerr := t.confirmOverwrite(ctx, filePath); cerr == nil {
				overwrite = ov
			}
		}
		if !overwrite {
			filePath = appendTimestamp(filePath)
		}
	}

	var oldContent *string
	existingData, err := os.ReadFile(filePath)
	if err != nil {
		if !os.IsNotExist(err) {
			return nil, fmt.Errorf("failed to read existing file %s: %w", filePath, err)
		}
	} else {
		existing := string(existingData)
		oldContent = &existing

		if toolCtx != nil && toolCtx.ReadFileState != nil {
			if !toolCtx.ReadFileState.Has(filePath) {
				return nil, fmt.Errorf("file has not been read yet. Read it first before writing to it")
			}
		}
	}

	dir := filepath.Dir(filePath)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	if err := os.WriteFile(filePath, []byte(content), 0o644); err != nil {
		return nil, fmt.Errorf("failed to write file %s: %w", filePath, err)
	}

	if toolCtx != nil && toolCtx.ReadFileState != nil {
		toolCtx.ReadFileState.Set(filePath, content)
	}

	var outputType string
	if oldContent != nil {
		outputType = "update"
	} else {
		outputType = "create"
	}

	output := FileWriteOutput{
		Type:         outputType,
		FilePath:     filePath,
		Content:      content,
		OriginalFile: oldContent,
	}

	return &tools.ToolResult{Data: output}, nil
}

func (t *FileWriteTool) Prompt(_ context.Context, _ tools.PromptOptions) (string, error) {
	return `Writes a file to the local filesystem.

Usage:
- This tool will overwrite the existing file if there is one at the path provided.
- If this is an existing file, you MUST use the Read tool first to read the file's contents. This tool will fail if you did not read the file first.
- The file_path parameter supports BOTH absolute paths and relative paths. Relative paths are resolved against the project directory automatically, so you can simply write 'report.xlsx' or 'scripts/gen.py' and it will be placed correctly.
- When the user EXPLICITLY asks you to generate files (e.g. data exports, reports, scripts, logs, compiled output), you are encouraged to create new files directly under the project directory. For example, if the user says '整理数据并写入 xls', write a Python script to an appropriate location in the project.
- For binary / structured output formats, use the Write + Bash/PowerShell pattern:
  - .xlsx / .xls:  write a Python script that uses 'openpyxl' or 'xlsxwriter' (pip install openpyxl xlsxwriter)
  - .docx / .doc:  write a Python script that uses 'python-docx' (pip install python-docx)
  - .pptx:         write a Python script that uses 'python-pptx' (pip install python-pptx)
  - .png / .jpg:   write a Python script that uses 'Pillow' or 'matplotlib' (pip install pillow matplotlib)
  - .pdf:          write a Python script that uses 'fpdf' or 'reportlab' (pip install fpdf reportlab)
  - .csv / .json:  can be written directly via this tool (they are text), no script needed
- ALWAYS prefer editing existing files in the codebase. NEVER write new files unless explicitly required by the user's request.
- NEVER proactively create documentation files (*.md) or README files. Only create documentation files if explicitly requested by the User.
- Even if you use a relative path, it is automatically resolved to an absolute path anchored at the project directory.
- auto_generated flag: set auto_generated=true when writing intermediate/helper files the agent creates on its own (e.g. a Python script that produces a final artifact). Such files get a unix-timestamp suffix (int64, seconds) appended to the filename to avoid collisions. Set auto_generated=false (default) for the final result file the user explicitly requested; if it already exists, the user is asked whether to overwrite, and if they decline a timestamp suffix is appended instead.`, nil
}

func isUNCPath(path string) bool {
	return strings.HasPrefix(path, "\\\\") || strings.HasPrefix(path, "//")
}

func expandPath(path string) string {
	if strings.HasPrefix(path, "~") {
		home, err := os.UserHomeDir()
		if err == nil {
			return filepath.Join(home, path[1:])
		}
	}
	abs, err := filepath.Abs(path)
	if err != nil {
		return path
	}
	return abs
}

func ParseFileWriteInput(raw map[string]any) (FileWriteInput, error) {
	inp := FileWriteInput{}
	if v, ok := raw["file_path"].(string); ok {
		inp.FilePath = v
	}
	if v, ok := raw["content"].(string); ok {
		inp.Content = v
	}
	if v, ok := raw["auto_generated"].(bool); ok {
		inp.AutoGenerated = v
	}
	if inp.FilePath == "" {
		return inp, fmt.Errorf("file_path is required")
	}
	return inp, nil
}

// appendTimestamp 在文件名扩展名前插入 unix 时间戳（int64 秒）后缀，
// 例如 report.xlsx -> report_1723136400.xlsx，gen.py -> gen_1723136400.py。
func appendTimestamp(path string) string {
	ext := filepath.Ext(path)
	base := strings.TrimSuffix(path, ext)
	return fmt.Sprintf("%s_%d%s", base, time.Now().Unix(), ext)
}
